@isTest
public class JsonToStripeObjectTest {

    @isTest
    private static void jsonToObjectTest(){
        
        String jsonStr='{"id":"cus_GWKDi3kCQz0s7T","object":"customer","address":null,"balance":0,"created":1578639969,"currency":"usd","default_source":null,"delinquent":false,"description":null,"discount":null,"email":null,"invoice_prefix":"3DE337E","invoice_settings":{"custom_fields":null,"default_payment_method":null,"footer":null},"livemode":false,"metadata":{},"name":null,"phone":null,"preferred_locales":[],"shipping":null,"sources":{"object":"list","data":[],"has_more":false,"url":"/v1/customers/cus_GWKDi3kCQz0s7T/sources"},"subscriptions":{"object":"list","data":[],"has_more":false,"url":"/v1/customers/cus_GWKDi3kCQz0s7T/subscriptions"},"tax_exempt":"none","tax_ids":{"object":"list","data":[],"has_more":false,"url":"/v1/customers/cus_GWKDi3kCQz0s7T/tax_ids"}}';
    	
        
    }
}