public class StripePlanObj {
    
    public String id {get;set;}
    public Decimal amount {get;set;}
    public String billingScheme {get;set;}
    public DateTime created {get;set;}
    public String currncy {get;set;}
    public String interval {get;set;}
    public Decimal intervalCount {get;set;}
    public String nickname {get;set;}
    public String product {get;set;}

    public StripePlanObj() {}
}